function Flash(){};Flash.Notes={};function Merge(a,b){for(var c in b)a[c]=b[c];return a}function randomPos(a){return Math.floor(Math.random()*a)}function saveData(a,b){Modernizr.localstorage&&localStorage.setItem(a,b)}function getData(a){if(Modernizr.localstorage)return localStorage.getItem(a)};Flash.Notes.AjaxUtilities=function(){var a,b,c=!1;this.createXHR=function(){a=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP")};this.getXHR=function(){return a};this.open=function(b,e){try{a.open(b,e,!0)}catch(f){c=!1}};this.send=function(b,e){try{a.setRequestHeader("Content-type","application/x-www-form-urlencoded"),a.send(e)}catch(f){c=!1}};this.onChange=function(){var d,e,f;if(a.readyState===4){if(a.status===200||a.statusText==="OK"){c=!0;try{b=a.responseXML;e=b.getElementsByTagName("score");
f=b.getElementsByTagName("time");ds=b.getElementsByTagName("date_string");ts=b.getElementsByTagName("time_string");for(d=0;d<e.length;d++)statusModel.top_scores[d]=e[d].childNodes[0].nodeValue,statusModel.top_times[d]=f[d].childNodes[0].nodeValue,statusModel.top_date_strings[d]=ds[d].childNodes[0].nodeValue,statusModel.top_time_strings[d]=ts[d].childNodes[0].nodeValue}catch(g){c=!1}}else c=!1;gameController.displayFinalScore(c);$("#main_menu_button").show()}}};$(document).ready(function(){var a="a,b,c,d,e,f,g".split(",");Modernizr.canvas?(cfg=new Flash.Notes.Config,statusModel=new Flash.Notes.StatusModel,statusView=new Flash.Notes.StatusView,notationModel=new Flash.Notes.NotationModel,notationController=new Flash.Notes.NotationController(0),gameController=new Flash.Notes.GameController,$("#stop").hide(),$("#menu_frame").show(),$("#practice_button").click(function(){gameController.displayPractice()}),$("#play_button").click(function(){gameController.displayGame()}),
$("#instructions_button").click(function(){$("#menu_frame").hide();$("#instructions_frame").show()}),$("#back_button").click(function(){$("#instructions_frame").hide();$("#menu_frame").show()}),$("#start_button").click(function(){gameController.getStart()||($(this).hide(),$("#stop_button").show());gameController.startGame("#status_timer")}),$("#stop_button").click(function(){gameController.getStart()&&($(this).hide(),$("#start_button").show());gameController.stopGame()}),$(".inputBtn").keydown(function(b){var c=
b.keyCode;c==="13"&&b.preventDefault();c>=65&&c<=71&&(b=a[c-65],gameController.continueGame(c,b))}),$(".inputBtn").click(function(){var b=$(this).attr("value").charCodeAt(0);gameController.continueGame(b,a[b-65])}),$(".clefBtn").click(function(){var a=parseInt($(this).attr("value"));gameController.toggleClef(a);$("#a").focus()}),$("#session_start_button").click(function(){$("#session_frame").hide();statusModel.setTimeout(!1);$("#game_frame").show();gameController.startGame("#status_timer")}),$("#session_summary_button").click(function(){$("#session_frame").hide();
gameController.displaySummary()}),$("#game_end_button").click(function(){$("#session_frame").hide();gameController.processFinalScore()}),$("#sum_continue_button").click(function(){$("#summary_frame").hide();$("#session_frame").hide();!statusModel.getTimeout()&&statusModel.getMode()===statusModel.GAME_MODE&&gameController.startGame("#timer");statusModel.getTimeout()?gameController.updateLevel():$("#game_frame").show();$("#a").focus()}),$("#quit_button").click(function(){$("#summary_frame").hide();
statusModel.getMode()===cfg.GAME_MODE?(gameController.processFinalScore(),gameController.removeLivesDisplay(),$("#score_display_frame").show()):$("#menu_frame").show()}),$("#main_menu_button").click(function(){$("#score_display_frame").hide();$("#main_menu_button").hide();gameController.init();$("#menu_frame").show()}),$("button").hover(function(){$(this).css({opacity:1})},function(){$(this).css({opacity:0.9})})):$("#nocanvas_frame").show()});Flash.Notes.GameController=function(){this.isMaxLevel=!1;this.init()};
Flash.Notes.GameController.prototype.init=function(){statusModel.start(!1);statusModel.setTimeout(!1);statusModel.setTimeInterval(cfg.TIMEOUT);statusModel.setLevel(1);statusModel.setPoints(0);statusModel.setAttempts(0);statusModel.setScore(0);statusModel.setLives(cfg.MAX_LIVES);statusView.displayTime("#status_timer",0);notationController.hideNote();notationController.drawClef(cfg.TREBLE);notationController.setLedgerLines(cfg.MIN_LEDGER);$("#start_button").hide();$("#stop_button").hide();this.initClefs(cfg.TREBLE);
this.displayScore();return this};Flash.Notes.GameController.prototype.setMode=function(a){statusModel.setMode(a)};Flash.Notes.GameController.prototype.initClefs=function(a){var b;for(b=0;b<4;b++)statusModel.active_clefs[b]=!1,statusModel.clefButtons[b].removeClass("on"),statusModel.clefButtons[b].addClass("off");statusModel.active_clefs[a]=!0;statusModel.clefButtons[a].removeClass("off");statusModel.clefButtons[a].addClass("on")};
Flash.Notes.GameController.prototype.startGame=function(a){var b=statusModel.getStart(),c=statusModel.getMode();statusModel.keyId="a";if(b)this.stopGame();else{statusModel.start(!0);document.getElementById("a").focus();switch(c){case cfg.GAME_MODE:this.startTimer(a,statusModel.getTimeInterval(),c);break;case cfg.PRACTICE_MODE:this.startTimer(a,0,c)}notationController.drawNote()}};
Flash.Notes.GameController.prototype.startTimer=function(a,b,c){var d=this;b<0?(clearTimeout(this.t),statusModel.setTimeout(!0),this.stopGame()):this.t=setTimeout(function(){d.updateTimer(a,b,c)},1E3);statusView.displayTime(a,b);return this};
Flash.Notes.GameController.prototype.updateTimer=function(a,b,c){statusModel.getStart()&&c===cfg.GAME_MODE?(b-=1,statusModel.setTime(b),statusModel.setTimeInterval(b),this.startTimer(a,b,c)):statusModel.getStart()&&c===cfg.PRACTICE_MODE&&(b+=1,statusModel.setTime(b),this.startTimer(a,b,c))};
Flash.Notes.GameController.prototype.continueGame=function(a,b){var c,d=statusModel.getStart(),e=statusModel.getLevel(),f=statusModel.getMode()===cfg.GAME_MODE?!0:!1;statusModel.keyCode=a-65;statusModel.value=notationController.getNoteValue();statusModel.keyId=b;c=this.isNoteMatched();f&&!c&&(statusModel.decLives(),statusModel.getLives(),statusView.updateLivesDisplay());d&&c&&(this.isMaxLevel?notationController.drawClef(notationController.getRandomClefType(4,0)):(e>=5&&e<=8&&notationController.drawClef(notationController.getRandomClefType(2,
0)),e>=13&&e<=16&&notationController.drawClef(notationController.getRandomClefType(2,2))),f||(this.setPracticeLedger(),notationController.drawClef(statusModel.getClefType())),notationController.drawNote(),statusModel.addPoint(),statusModel.calculateScore());d&&(statusModel.addAttempt(),this.displayScore(),document.getElementById(b).focus())};
Flash.Notes.GameController.prototype.stopGame=function(){var a,b;statusModel.start(!1);notationController.hideNote();document.getElementById(statusModel.keyId).blur();statusModel.getMode()===cfg.GAME_MODE?(a=statusModel.isLevelAdvance(),b=statusModel.getLives()>0?!1:!0,a&&(statusModel.advanceLevel(),statusModel.addBonus()),this.displaySessionAlert(!1,b,a)):(notationController.setLedgerLines(cfg.MIN_LEDGER),$("#stop_button").hide(),$("#start_button").show(),this.displaySummary());return this};
Flash.Notes.GameController.prototype.resetGame=function(){statusModel.setTimeout(!1);statusModel.setTimeInterval(cfg.TIMEOUT);statusModel.setPoints(0);statusModel.setAttempts(0);this.displayScore()};Flash.Notes.GameController.prototype.getStart=function(){return statusModel.getStart()};Flash.Notes.GameController.prototype.isNoteMatched=function(){return statusModel.match()};
Flash.Notes.GameController.prototype.toggleClef=function(a){switch(statusModel.toggleClefButton(a)){case cfg.TOGGLE_ON:statusModel.clefButtons[a].removeClass("off");statusModel.clefButtons[a].addClass("on");notationController.drawClef(a);break;case cfg.TOGGLE_OFF:statusModel.clefButtons[a].removeClass("on"),statusModel.clefButtons[a].addClass("off"),notationController.drawClef(statusModel.getClefType())}};
Flash.Notes.GameController.prototype.setPracticeLedger=function(){var a=statusModel.getPercent(),b=statusModel.getAttempts(),c=notationController.getLedgerLines();a>=cfg.P_HIGH_PCT&&b%cfg.PRACTICE_ATT===0&&c<cfg.MAX_LEDGER&&notationController.setLedgerLines(c+1);a<cfg.P_LOW_PCT&&c>cfg.MIN_LEDGER&&notationController.setLedgerLines(c-1)};
Flash.Notes.GameController.prototype.updateLevel=function(){var a=statusModel.getLevel(),b=a%2===0?a/2-1:Math.floor(a/2),c;statusModel.setGameClefTypes();c=statusModel.getClefType();b%=4;if(a===cfg.MAX_LEVEL)this.isMaxLevel=!0,notationController.drawClef(notationController.getRandomClefType(4,0)),notationController.setLedgerLines(3);else{switch(c){case cfg.RANDOM_TB:notationController.drawClef(notationController.getRandomClefType(2,0));break;case cfg.RANDOM_AT:notationController.drawClef(notationController.getRandomClefType(2,
2));break;default:notationController.drawClef(c)}notationController.setLedgerLines(b)}statusModel.getTimeout()&&this.resetGame();this.displayScore();this.displaySessionAlert(!0,!1,!1)};Flash.Notes.GameController.prototype.displayPractice=function(){this.init();this.setMode(cfg.PRACTICE_MODE);$("#menu_frame").hide();$("#status_level_label").html("");$("#status_level").html("");$("#game_frame").show();$("#menu_buttons").show();$("#game_status_box").hide();$("#stop_button").hide();$("#start_button").show()};
Flash.Notes.GameController.prototype.displayGame=function(){this.init();this.setMode(cfg.GAME_MODE);statusView.initLivesDisplay("game_lives",cfg.MAX_LIVES);this.displaySessionAlert(!0,!1,!1)};
Flash.Notes.GameController.prototype.displayScore=function(){statusView.displayPoints("#status_points",statusModel.getPoints(),statusModel.getAttempts());statusView.displayPercent("#status_percent",statusModel.getPoints(),statusModel.getAttempts());statusView.displayScore("#status_score",statusModel.getScore());statusModel.getMode()===cfg.GAME_MODE&&statusView.displayLevel("#status_level",statusModel.getLevel());statusView.displayHiScore("#hi_score",statusModel.getHiScore())};
Flash.Notes.GameController.prototype.displaySummary=function(){var a;$("#game_frame").hide();statusView.displayPoints("#point_summary",statusModel.getPoints(),statusModel.getAttempts());statusView.displayPercent("#percent_summary",statusModel.getPoints(),statusModel.getAttempts());statusModel.getMode()===cfg.PRACTICE_MODE&&($("#score_summary_row").hide(),$("#level_summary_row").hide(),$("#lives_summary_row").hide(),$("#next_level_row").hide(),$("#continue_btn").hide(),$("#time_summary_row").show(),
a=statusModel.getTime()?statusModel.getTime():0,$("#time_summary").html(""+a+" sec"));statusModel.getMode()===cfg.GAME_MODE&&(statusView.displayScore("#score_summary",statusModel.getScore()),$("#time_summary_row").hide(),$("#score_summary_row").show(),$("#level_summary_row").show(),$("#lives_summary_row").show(),$("#next_level_row").show(),$("#level_summary").html(""+statusModel.getLevel()),$("#lives_summary").html(""+statusModel.getLives()));$("#summary_frame").show()};
Flash.Notes.GameController.prototype.removeLivesDisplay=function(){statusModel.getMode()===cfg.GAME_MODE&&statusView.removeLivesDisplay()};
Flash.Notes.GameController.prototype.displaySessionAlert=function(a,b,c){$("#menu_frame").hide();$("#instructions_frame").hide();$("#summary_frame").hide();$("#game_frame").hide();$("#menu_buttons").hide();$("#session_frame").show();$("#game_status_box").show();a&&!b?($("#session_start_header").html("Level "+statusModel.getLevel()),$("#session_end").hide(),$("#session_summary_button").hide(),$("#game_end").hide(),$("#session_start").show()):b?($("#session_start").hide(),$("#session_end").hide(),$("#session_summary_button").hide(),
$("#game_end").show()):($("#session_start").hide(),$("#game_end").hide(),a=statusModel.getLives(),a=a>1?" lives":" life",$("#lives").html(""+statusModel.getLives()+a+" left"),c?$("#bonus").html("BONUS PTS<br/>"+statusModel.getBonus()):$("#bonus").html(""),$("#session_end").show(),$("#session_summary_button").show())};
Flash.Notes.GameController.prototype.processFinalScore=function(){var a,b;a=statusModel.getScore();var c,d;statusModel.setDate();b=statusModel.getDateTime();c=statusModel.getDateString();d=statusModel.getTimeString();b="score="+a+"&time="+b+"&date_string="+c+"&time_string="+d;Modernizr.localstorage&&(c=statusModel.getHiScore(),a=c>a?c:a);statusModel.setHiScore(a);$("#score_text").html("Please wait . . . retrieving scores");ajaxUtilities.createXHR();a=ajaxUtilities.getXHR();ajaxUtilities.open("POST",
"php/get_scores.php");a.onreadystatechange=ajaxUtilities.onChange;ajaxUtilities.send("POST",b)};
Flash.Notes.GameController.prototype.displayFinalScore=function(a){var b,c,d,e="",f="",g="",h="your score: "+statusModel.getScore(),i=statusModel.top_scores.length;if(a)for(a=0;a<i;a++)b=parseInt(statusModel.top_scores[a]),c=statusModel.top_date_strings[a],d=parseInt(statusModel.top_times[a]),b===statusModel.getScore()&&d===statusModel.getDateTime()?(e+='<span class="your_scores">'+(a+1)+".</span><br />",f+='<span class="your_scores">'+b+"*</span><br />",g+='<span class="your_scores">'+c+"</span><br />",
h="* your score"):(e+=a+1+".<br />",f+=b+"<br />",g+=c+"<br />");else for(a=0;a<10;a++)e+=a+1+".<br />",f+="unavailable<br />",g+="unavailable<br />";$("#score_display_frame").show();$("#top_rank").html(e);$("#top_scores").html(f);$("#top_dates").html(g);$("#top_score_footer").html(h)};Flash.Notes.NotationController=function(a){this.nv=new Flash.Notes.NotationView("staff_box",350,240);this.llShow=this.noteShow=!1;this.drawStaff();this.setLedgerLines(a)};
Flash.Notes.NotationController.prototype.drawStaff=function(){this.staffPaper=this.nv.paper;this.nv.box.fillRect(this.nv.RECT_X,this.nv.RECT_Y,this.nv.RECT_W,this.nv.RECT_H);this.staffBox=this.nv.box.getRect();this.staffPaper.path(this.nv.staffPath());this.clefObj=this.nv.clef(cfg.TREBLE,notationModel.getImgUrl(cfg.TREBLE));notationModel.setClefType(cfg.TREBLE);notationModel.setNoteValOffset(cfg.TREBLE_OFFSET);this.clefImg=this.staffPaper.image(this.clefObj.src,this.clefObj.x,this.clefObj.y,this.clefObj.w,
this.clefObj.h);this.staffPaper.image("images/fn_logo.png",this.nv.RECT_X-42,this.nv.RECT_Y,40,this.nv.RECT_H)};Flash.Notes.NotationController.prototype.drawClef=function(a){this.clefObj=this.nv.clef(a,notationModel.getImgUrl(a));notationModel.setClefType(a);notationModel.setNoteValOffset(notationModel.getClefOffset(a));this.clefImg.hide();this.clefImg=this.staffPaper.image(this.clefObj.src,this.clefObj.x,this.clefObj.y,this.clefObj.w,this.clefObj.h);this.clefImg.show()};
Flash.Notes.NotationController.prototype.drawNote=function(){var a=randomPos(this.nv.PROPS.numPos),b=this.nv.note(a,this.nv.staff);notationModel.setNotePos(a);this.noteShow&&this.noteImg.hide();this.noteImg=this.staffPaper.image(b.src,b.x,b.y,b.w,b.h);this.noteImg.show();this.noteShow=!0;if(this.llShow)this.ledgerLineImg.hide(),this.llShow=!1;a=this.nv.staff.ledgerLines(a);if(a!=0)b=this.nv.ledgerLinePath(a,b),this.ledgerLineImg=this.staffPaper.path(b),this.ledgerLineImg.show(),this.llShow=!0};
Flash.Notes.NotationController.prototype.hideNote=function(){if(this.llShow)this.ledgerLineImg.hide(),this.llShow=!1;this.noteShow&&this.noteImg.hide()};Flash.Notes.NotationController.prototype.getNoteValue=function(){return notationModel.getNoteValue()};Flash.Notes.NotationController.prototype.setLedgerLines=function(a){notationModel.setLedgerLines(a);this.nv.PROPS.ledgerLines=a;this.nv.PROPS.numPos=11+4*a;this.nv.staff.setLedgerLines(a);this.nv.staff.setNumOfPositions()};
Flash.Notes.NotationController.prototype.getLedgerLines=function(){return notationModel.getLedgerLines()};Flash.Notes.NotationController.prototype.getRandomClefType=function(a,b){return notationModel.randomClefType(a,b)};Flash.Notes.Config=function(){this.TREBLE=0;this.BASS=1;this.ALTO=2;this.TENOR=3;this.TREBLE_OFFSET=10;this.BASS_OFFSET=12;this.ALTO_OFFSET=11;this.TENOR_OFFSET=9;this.PRACTICE_MODE=0;this.GAME_MODE=1;this.MAX_LEVEL=17;this.TIER_1=4;this.TIER_2=8;this.TIER_3=12;this.TIER_4=16;this.MIN_ATTEMPTS=5;this.MIN_PERCENT=80;this.TIMEOUT=12;this.BONUS_INC=this.BONUS=50;this.BONUS_LEVEL=12;this.MAX_LIVES=5;this.RANDOM_TB=4;this.RANDOM_AT=5;this.RANDOM_ALL=6;this.TOGGLE_OFF=0;this.TOGGLE_ON=1;this.TOGGLE_NONE=
-1;this.MIN_LEDGER=0;this.MAX_LEDGER=3;this.P_HIGH_PCT=70;this.P_LOW_PCT=60;this.PRACTICE_ATT=5};Flash.Notes.NotationModel=function(){this.ledgerLines=this.valOffset=this.notePos=0;this.clefType=this.noteValue=-1;this.clefArray=[cfg.TREBLE,cfg.BASS,cfg.ALTO,cfg.TENOR]};Flash.Notes.NotationModel.prototype.getNoteValue=function(){return this.noteValue=this.notePos+(this.valOffset-2*this.ledgerLines)};Flash.Notes.NotationModel.prototype.setClefType=function(a){this.clefType=a;return this};Flash.Notes.NotationModel.prototype.getClefType=function(){return this.clefType};
Flash.Notes.NotationModel.prototype.setNoteValOffset=function(a){this.valOffset=a;return this};Flash.Notes.NotationModel.prototype.getNoteValOffset=function(){return this.valOffset};Flash.Notes.NotationModel.prototype.setNotePos=function(a){this.notePos=a;return this};Flash.Notes.NotationModel.prototype.getNotePos=function(){return this.notePos};Flash.Notes.NotationModel.prototype.setLedgerLines=function(a){this.ledgerLines=a;return this};Flash.Notes.NotationModel.prototype.getLedgerLines=function(){return this.ledgerLines};
Flash.Notes.NotationModel.prototype.randomClefType=function(a,b){return this.clefArray[Math.round(Math.random()*100)%a+b]};Flash.Notes.NotationModel.prototype.practiceClefType=function(){return this.clefArray[Math.round(Math.random()*100)%range+offset]};Flash.Notes.NotationModel.prototype.getImgUrl=function(a){switch(a){case cfg.TREBLE:return"images/treble.png";case cfg.BASS:return"images/bass.png";case cfg.ALTO:return"images/c_clef.png";case cfg.TENOR:return"images/c_clef.png";default:return"images/treble.png"}};
Flash.Notes.NotationModel.prototype.getClefOffset=function(a){switch(a){case cfg.TREBLE:return cfg.TREBLE_OFFSET;case cfg.BASS:return cfg.BASS_OFFSET;case cfg.ALTO:return cfg.ALTO_OFFSET;case cfg.TENOR:return cfg.TENOR_OFFSET;default:return cfg.TREBLE_OFFSET}};Flash.Notes.StatusModel=function(){if(Modernizr.localstorage){var a=parseInt(localStorage.getItem("hiscore"));this.hi_score=a?a:0}else this.hi_score=0;this.obj=this;this.bonus=this.score=this.level=this.attempts=this.points=0;this.top_scores=[];this.top_times=[];this.top_date_strings=[];this.top_time_strings=[];this.go=!1;this.lives=5;this.numOfCodes=7;this.timeInterval=cfg.TIMEOUT;this.timeOut=!1;this.session_count=0;this.active_clefs=[!0,!1,!1,!1];this.clefArray=[cfg.TREBLE,cfg.BASS,cfg.ALTO,cfg.TENOR];
this.clefButtons=[$("#treble_button"),$("#bass_button"),$("#alto_button"),$("#tenor_button")]};Flash.Notes.StatusModel.prototype.start=function(a){this.go=a;return this};Flash.Notes.StatusModel.prototype.getStart=function(){return this.go};Flash.Notes.StatusModel.prototype.setMode=function(a){this.mode=a;return this};Flash.Notes.StatusModel.prototype.getMode=function(){return this.mode};Flash.Notes.StatusModel.prototype.setTimeInterval=function(a){this.timeInterval=a;return this};
Flash.Notes.StatusModel.prototype.getTimeInterval=function(){return this.timeInterval};Flash.Notes.StatusModel.prototype.setTime=function(a){this.time=a;return this};Flash.Notes.StatusModel.prototype.getTime=function(){return this.time};Flash.Notes.StatusModel.prototype.setTimeout=function(a){this.timeOut=a;return this};Flash.Notes.StatusModel.prototype.getTimeout=function(){return this.timeOut};Flash.Notes.StatusModel.prototype.addPoint=function(){this.points+=1;return this};
Flash.Notes.StatusModel.prototype.setPoints=function(a){this.points=a;return this};Flash.Notes.StatusModel.prototype.getPoints=function(){return this.points};Flash.Notes.StatusModel.prototype.addAttempt=function(){this.attempts+=1;return this};Flash.Notes.StatusModel.prototype.setAttempts=function(a){this.attempts=a};Flash.Notes.StatusModel.prototype.getAttempts=function(){return this.attempts};Flash.Notes.StatusModel.prototype.getPercent=function(){return Math.floor(this.points/this.attempts*100)};
Flash.Notes.StatusModel.prototype.calculateScore=function(){this.score+=this.points*this.level;return this};Flash.Notes.StatusModel.prototype.addBonus=function(){this.bonus=cfg.BONUS*this.level;this.score+=this.bonus;return this};Flash.Notes.StatusModel.prototype.getBonus=function(){return this.bonus};Flash.Notes.StatusModel.prototype.setScore=function(a){this.score=a;return this};Flash.Notes.StatusModel.prototype.getScore=function(){return this.score};
Flash.Notes.StatusModel.prototype.getHiScore=function(){return this.hi_score};Flash.Notes.StatusModel.prototype.setHiScore=function(a){this.hi_score=a;Modernizr.localstorage&&localStorage.setItem("hiscore",this.hi_score);return this};Flash.Notes.StatusModel.prototype.setDate=function(){this.date=new Date;this.date_time=this.date.getTime()};Flash.Notes.StatusModel.prototype.getDateTime=function(){return this.date_time};
Flash.Notes.StatusModel.prototype.getDateString=function(){var a=""+(this.date.getMonth()+1),b=this.date.getDate()<10?"0"+this.date.getDate():this.date.getDate();return a+"-"+b+"-"+this.date.getFullYear()};Flash.Notes.StatusModel.prototype.getTimeString=function(){var a=""+this.date.getHours(),b=this.date.getMinutes()<10?"0"+this.date.getMinutes():this.date.getMinutes(),c=this.date.getSeconds()<10?"0"+this.date.getSeconds():this.date.getSeconds();return a+":"+b+":"+c};
Flash.Notes.StatusModel.prototype.setLevel=function(a){this.level=a;this.level>cfg.BONUS_LEVEL&&(cfg.BONUS+=cfg.BONUS_INC);return this};Flash.Notes.StatusModel.prototype.getLevel=function(){return this.level};Flash.Notes.StatusModel.prototype.advanceLevel=function(){this.setLevel(this.level<cfg.MAX_LEVEL?this.level+=1:cfg.MAX_LEVEL);return this};
Flash.Notes.StatusModel.prototype.isLevelAdvance=function(){return this.getPercent()>=cfg.MIN_PERCENT&&this.getTimeout()&&this.getAttempts()>=cfg.MIN_ATTEMPTS?!0:!1};Flash.Notes.StatusModel.prototype.setGameClefTypes=function(){var a,b=this.getLevel();b<=cfg.TIER_1&&(a=b%2===0,a=[!a,a,!1,!1]);b>cfg.TIER_1&&b<=cfg.TIER_2&&(a=[!0,!0,!1,!1]);b>cfg.TIER_2&&b<=cfg.TIER_3&&(a=b%2===0,a=[!1,!1,!a,a]);b>cfg.TIER_3&&b<=cfg.TIER_4&&(a=[!1,!1,!0,!0]);b>cfg.TIER_4&&(a=[!0,!0,!0,!0]);this.set_clef(a)};
Flash.Notes.StatusModel.prototype.set_clef=function(a){var b;for(b=0;b<4;b++)this.active_clefs[b]=a[b]};Flash.Notes.StatusModel.prototype.getClefType=function(){var a,b=[],c=0;for(a=0;a<4;a++)this.active_clefs[a]===!0&&(b[c]=a,c+=1);b.length===1?a=b[0]:(a=Math.round(Math.random()*100)%b.length,a=b[a]);return this.clefArray[a]};
Flash.Notes.StatusModel.prototype.toggleClefButton=function(a){var b,c=0;if(this.active_clefs[a]){for(b=0;b<4;b++)c+=this.active_clefs[b]===!0?1:0;if(c===1)return cfg.TOGGLE_NONE}this.active_clefs[a]=!this.active_clefs[a];return this.active_clefs[a]?cfg.TOGGLE_ON:cfg.TOGGLE_OFF};Flash.Notes.StatusModel.prototype.decLives=function(){this.lives-=1;if(this.lives<0)this.lives=0;return this};Flash.Notes.StatusModel.prototype.setLives=function(a){this.lives=a;return this};
Flash.Notes.StatusModel.prototype.getLives=function(){return this.lives};Flash.Notes.StatusModel.prototype.match=function(){this.value%=this.numOfCodes;return this.value===this.keyCode?!0:!1};Flash.Notes.NotationView=function(a,b,c){this.PROPS={numLines:5,space:14,ledgerLines:1,numPos:15};this.box=new Flash.Notes.Box(a,b,c);this.paper=this.box.ctx();this.RECT_X=42;this.RECT_Y=0;this.RECT_W=b-42;this.RECT_H=(6+2*this.PROPS.ledgerLines+this.PROPS.numLines+1)*this.PROPS.space;this.STAFF_X=this.RECT_X+10;this.STAFF_Y=this.RECT_Y+(4+this.PROPS.ledgerLines)*this.PROPS.space;this.STAFF_W=this.RECT_W-20;this.staff=new Flash.Notes.Staff(this.STAFF_X,this.STAFF_Y,this.STAFF_W,this.PROPS);this.valueOffset=
this.clefType=this.notePos=-1};Flash.Notes.NotationView.prototype.staffPath=function(){return this.staff.path()};Flash.Notes.NotationView.prototype.clef=function(a,b){return new Flash.Notes.Clef(this.STAFF_X,this.STAFF_Y,this.PROPS.space,a,b)};Flash.Notes.NotationView.prototype.note=function(a,b){var c=new Flash.Notes.Note(this.STAFF_X+this.STAFF_W/2,b.bottomPos(),a,this.PROPS.space,"images/whole.png");this.pos=a;return c};
Flash.Notes.NotationView.prototype.ledgerLinePath=function(a,b){var c=0,d=Math.abs(a),e="";a>0&&(c=1);a<0&&(c=-1);switch(c){case 1:e+=b.ledgerPath(this.STAFF_Y+5*this.PROPS.space,d,c);break;case -1:e+=b.ledgerPath(this.STAFF_Y-this.PROPS.space,d,c)}return e};Flash.Notes.StatusView=function(){this.dots=[]};Flash.Notes.StatusView.prototype.drawStatusBar=function(a,b,c,d){this.status_paper=Raphael(a,b,c,d);this.box=this.status_paper.rect(0,0,c,d);this.box.attr({stroke:"red",fill:"#202000"})};Flash.Notes.StatusView.prototype.displayTime=function(a,b){var c="00:",d=b>=0?""+b:""+(b+1);b<10&&(c="00:0");$(a).html(c+d)};Flash.Notes.StatusView.prototype.displayLevel=function(a,b){var c;$(a).html(""+b)};
Flash.Notes.StatusView.prototype.displayPoints=function(a,b,c){$(a).html(""+b+"/"+c)};Flash.Notes.StatusView.prototype.displayPercent=function(a,b,c){b=""+(c>0?Math.round(b/c*100):0)+"%";$(a).html(b)};Flash.Notes.StatusView.prototype.displayScore=function(a,b){var c;$(a).html(""+b)};Flash.Notes.StatusView.prototype.displayHiScore=function(a,b){var c;$(a).html(""+b)};
Flash.Notes.StatusView.prototype.initLivesDisplay=function(a,b){var c;this.lives_paper=Raphael(a,60,20);for(c=0;c<b;c++)this.dots[c]=this.lives_paper.circle(10*(c+1),5,4.5).attr({fill:"red",stroke:"black"})};Flash.Notes.StatusView.prototype.updateLivesDisplay=function(){var a=this.dots.length;a>0&&(this.dots[a-1].remove(),this.dots.pop())};Flash.Notes.StatusView.prototype.removeLivesDisplay=function(){this.lives_paper.remove()};Flash.Notes.Box=function(a,b,c){arguments.length>0&&this.init(a,b,c)};Flash.Notes.Box.prototype.init=function(a,b,c){this.x=document.getElementById(a).getAttribute("left");this.y=document.getElementById(a).getAttribute("top");this.width=b;this.height=c;this.paper=Raphael(a,this.width,this.height);this.attributes={stroke_width:0,fill:"beige",stroke:"beige"};this.bg_attributes={stroke_width:0,fill:"white",stroke:"white"}};Flash.Notes.Box.prototype.ctx=function(){return this.paper};
Flash.Notes.Box.prototype.setStrokeColor=function(a){this.attributes.stroke=a;return this};Flash.Notes.Box.prototype.setStrokeWidth=function(a){this.attributes.stroke_width=a;return this};Flash.Notes.Box.prototype.setFill=function(a){this.attributes.fill=a;return this};Flash.Notes.Box.prototype.fillRect=function(a,b,c,d){d<0&&(b+=d,d=-d);this.rectangle=this.paper.rect(a,b,c,d).attr(this.attributes);return this};Flash.Notes.Box.prototype.getRect=function(){return this.rectangle};Flash.Notes.Clef=function(a,b,c,d,e){this.src=e;this.x=a+0.35*c;this.y=b;this.offset=this.w=this.h=0;switch(d){case 0:this.y=b-1.25*c;this.h=6.7*c;this.w=0.4*this.h;this.offset=10;break;case 1:this.h=3.4*c;this.w=0.69*this.h;this.offset=12;break;case 2:this.h=4*c;this.w=0.75*this.h;this.offset=11;break;case 3:this.y=b-c,this.h=4*c,this.w=0.75*this.h,this.offset=9}};Flash.Notes.Note=function(a,b,c,d,e){this.x=a;this.y=b-c*d/2;this.h=d;this.w=1.6*this.h;this.src=e};Flash.Notes.Note.prototype.ledgerPath=function(a,b,c){for(var d="",e=this.x-this.w/4,f=this.x+this.w+this.w/4,g=0;g<b;g++){var h=a+g*c*this.h;d+="M "+e+", "+h+" L "+f+", "+h}return d};Flash.Notes.Staff=function(a,b,c,d){this.x=a;this.y=b;this.w=c;this.props={numOfLines:5,space:18,ledgerLines:3,numOfPositions:23};this.TREBLE=0;this.BASS=1;this.ALTO=2;this.TENOR=3;Merge(this.props,d)};Flash.Notes.Staff.prototype.path=function(){for(var a="",b=this.getNumOfLines(),c=this.x,d=this.x+this.w,e=0;e<b;e++){var f=this.y+e*this.getSpace();a+="M "+c+" "+f+" L "+d+" "+f}return a};Flash.Notes.Staff.prototype.getProps=function(){return this.props};
Flash.Notes.Staff.prototype.setNumOfLines=function(a){this.props.numOfLines=a;return this};Flash.Notes.Staff.prototype.setSpace=function(a){this.props.space=a;return this};Flash.Notes.Staff.prototype.setLedgerLines=function(a){this.props.ledgerLines=a;return this};Flash.Notes.Staff.prototype.setNumOfPositions=function(){this.props.numOfPositions=2*(this.getNumOfLines+2*this.getLedgerLines())+1;return this};Flash.Notes.Staff.prototype.getNumOfLines=function(){return this.props.numOfLines};
Flash.Notes.Staff.prototype.getSpace=function(){return this.props.space};Flash.Notes.Staff.prototype.getLedgerLines=function(){return this.props.ledgerLines};Flash.Notes.Staff.prototype.getNumOfPositions=function(){return this.props.numOfPositions};Flash.Notes.Staff.prototype.bottomPos=function(){return this.y+(this.getNumOfLines()-1+this.getLedgerLines())*this.getSpace()};Flash.Notes.Staff.prototype.topPos=function(){return this.y-(this.getLedgerLines()+1)*this.getSpace()};
Flash.Notes.Staff.prototype.ledgerLines=function(a){var b=2*this.getLedgerLines()-1,c=2*(this.getLedgerLines()+this.getNumOfLines())+1,d=0;a<=b&&(d=1+Math.floor((b-a)/2));a>=c&&(d=-1-Math.floor((a-c)/2));return d};Flash.Notes.Staff.prototype.getPosY=function(a){return a>this.getNumOfPositions()-1?this.getTopPos():a<0?this.getBottomPos():this.getBottomPos()+a*(this.getSpace()/2)};
